# Site settings
title: Travis J. Warren
description: > # this means to ignore newlines until "baseurl:"
  Dad, sports lover and I.T guy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://travisjwarren.github.io" # the base hostname & protocol for your site
twitter_username: travisjwarren
github_username:  travisjwarren

# Build settings
markdown: kramdown
