# Site settings
title: CatThree
description: > # this means to ignore newlines until "baseurl:"
    a technology business created to find solutions to improve team and individual performance needs.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://travisjwarren.github.io" # the base hostname & protocol for your site
twitter_username: travisjwarren
github_username:  travisjwarren

# Build settings
markdown: kramdown
